# Generated by Django 4.1.7 on 2023-02-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_plaers',
            new_name='max_players',
        ),
    ]
