# Generated by Django 4.1.7 on 2023-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('bg', models.ImageField(upload_to='images/')),
                ('bgcaption', models.CharField(max_length=20, unique=True)),
                ('card_type1_name', models.CharField(default='Card Type 1', max_length=20)),
                ('card_type1_image', models.ImageField(blank=True, null=True, upload_to='card_types/')),
                ('card_type2_name', models.CharField(default='Card Type 2', max_length=20)),
                ('card_type2_image', models.ImageField(blank=True, null=True, upload_to='card_types/')),
                ('card_type3_name', models.CharField(default='Card Type 3', max_length=20)),
                ('card_type3_image', models.ImageField(blank=True, null=True, upload_to='card_types/')),
                ('card_type4_name', models.CharField(default='Card Type 4', max_length=20)),
                ('card_type4_image', models.ImageField(blank=True, null=True, upload_to='card_types/')),
                ('shop_name', models.CharField(default='Card Type 4', max_length=20)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='card_types/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
