# Generated by Django 4.1.7 on 2023-04-01 15:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='bg',
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='card_type1_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='card_type2_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='card_type3_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='card_type4_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
