# Generated by Django 4.1.7 on 2023-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_shopitem_image_alter_template_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='card_type1_mvdown',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type1_mvup',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type3_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type4_round_stop',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='start_balance',
            field=models.IntegerField(default=1000),
        ),
    ]
