# Generated by Django 4.1.7 on 2023-04-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_card_type1_mvdown_template_card_type2_mvdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='template',
            name='bgcaption',
        ),
    ]
