# Generated by Django 4.1.7 on 2023-04-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_template_bg_remove_template_bgcaption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='card_type1_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='card_type2_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='card_type3_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='card_type4_name',
        ),
    ]
