# Generated by Django 4.1.7 on 2023-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
