# Generated by Django 4.1.7 on 2023-04-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_room_is_last_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_last_player',
        ),
    ]
