# Generated by Django 4.1.7 on 2023-04-15 12:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_room_is_last_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='card_type1_mvup_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type2_mvdown_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type5_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type5_max',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='template',
            name='card_type5_min',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='template',
            name='reward_per_round',
            field=models.IntegerField(default=500),
        ),
    ]
