# Generated by Django 4.1.7 on 2023-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_template_card_type1_mvup_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='template',
            name='number_of_rounds',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='template',
            name='winning_amt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='winning_pos1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='winning_pos2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
