# Generated by Django 4.1.7 on 2023-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='author',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
