# Generated by Django 4.1.7 on 2023-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_room_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='diff_items_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='inventory_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rounds_frozen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='card_type1_pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='card_type2_pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='card_type3_pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='card_type4_pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='card_type5_pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='current_turn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='shop_pos',
            field=models.IntegerField(default=1),
        ),
    ]
