# Generated by Django 4.1.7 on 2023-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logged_at',
            field=models.CharField(default='', max_length=50),
        ),
    ]
