# Generated by Django 4.1.7 on 2023-05-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
